import os
import httpx
import asyncio
import logging
import base64
from typing import List, Dict, Any, Optional
from google import genai
from google.adk import Agent
from google.genai import types as genai_types
from google.adk.events import Event
from langsmith import traceable
from dotenv import load_dotenv

from authenticated_httpx import create_authenticated_client

load_dotenv()

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# MCP Server URLs
DB_URL = os.getenv("MCP_DB_SERVER_URL", "http://localhost:8010")
CODE_URL = os.getenv("MCP_CODE_SERVER_URL", "http://localhost:8013")
FS_URL = os.getenv("MCP_FS_SERVER_URL", "http://localhost:8014")

# Initialize GenAI client
genai_client = genai.Client(
    vertexai=True, 
    project=os.getenv("GCP_PROJECT_ID"), 
    location=os.getenv("GOOGLE_CLOUD_LOCATION", "global")
)


# --- Viz Tools ---

@traceable(run_type="tool", name="Viz_GenerateAndUpload")
async def generate_and_upload_chart(session_id: str, code: str, chart_name: str) -> Dict[str, Any]:
    """Unified tool: Generates a chart via Code MCP and uploads it to FS MCP. Returns the public URL."""
    try:
        # 1. Generate the chart
        async with create_authenticated_client(CODE_URL) as code_client:
            code_res = await code_client.post(f"{CODE_URL}/tools/execute_python", json={"code": code}, timeout=60.0)
            code_res.raise_for_status()
            code_data = code_res.json()
            
            images = code_data.get("generated_images", {})
            if not images:
                return {"error": "No images were generated by the code. Ensure your script saves a .png file."}
            
            # Take the first image found
            img_name = list(images.keys())[0]
            base64_data = images[img_name]

        # 2. Upload to GCS - Sanitize filename
        clean_name = "".join([c if c.isalnum() else "_" for c in chart_name.strip()])
        file_path = f"charts/{session_id.strip()}_{clean_name}.png"
        
        async with create_authenticated_client(FS_URL) as fs_client:
            fs_res = await fs_client.post(f"{FS_URL}/tools/gcs_write", json={
                "file_path": file_path,
                "content": base64_data,
                "content_type": "image/png"
            })
            fs_res.raise_for_status()
            return fs_res.json() # Contains public_url

    except Exception as e:
        logger.error(f"Unified Viz Error: {e}")
        return {"error": str(e)}

@traceable(run_type="tool", name="Viz_GetCitations")
async def get_session_citations(session_id: str) -> List[Dict[str, Any]]:
    """Fetch all research citations for the session to extract data for analysis."""
    try:
        async with create_authenticated_client(DB_URL) as client:
            response = await client.post(f"{DB_URL}/tools/get_session_citations", json={"session_id": session_id.strip()}, timeout=30.0)
            response.raise_for_status()
            return response.json().get("results", [])
    except Exception as e:
        logger.error(f"DB MCP Error (viz): {e}")
        return []

@traceable(run_type="tool", name="Viz_RecordChartURL")
async def record_chart_citation(session_id: str, chart_url: str, description: str) -> str:
    """Record the generated chart URL into the citation database."""
    try:
        async with create_authenticated_client(DB_URL) as client:
            # 1. Get model_run_id for the viz agent
            sql_ins = "INSERT INTO model_runs (session_id, agent_name, model_id) VALUES (:session_id, :agent_name, :model_id) RETURNING id"
            res_ins = await client.post(f"{DB_URL}/tools/sql_query", json={
                "sql": sql_ins,
                "params": {"session_id": session_id.strip(), "agent_name": "VisualizationAgent", "model_id": "gemini-2.5-flash"}
            })
            res_ins.raise_for_status()
            model_run_id = res_ins.json()["results"][0]["id"]

            # 2. Insert citation
            sql_cit = "INSERT INTO citations (model_run_id, source_url, source_type, title, snippet) VALUES (:model_run_id, :source_url, 'chart', :title, :snippet)"
            params_cit = {
                "model_run_id": model_run_id,
                "source_url": chart_url,
                "title": "Generated Visualization",
                "snippet": f"Visualization created for {description}"
            }
            await client.post(f"{DB_URL}/tools/sql_execute", json={"sql": sql_cit, "params": params_cit})
            return "SUCCESS: Chart URL recorded."
    except Exception as e:
        logger.error(f"DB Error (viz): {e}")
        return f"ERROR: {str(e)}"

# Visualization Agent: Gemini 2.5 Flash
VisualizationAgent = Agent(
    name="VisualizationAgent",
    model="gemini-2.5-flash",
    description="Specialist in data analysis and chart generation.",
    instruction=(
        "You are the Conclave Visualization Specialist. Your job is to create a visual chart based on research gathered by other agents.\n\n"
        "1. Identify the 'SESSION_ID' and 'QUESTION' from the prompt.\n"
        "2. Use 'get_session_citations' to retrieve the raw data gathered during the research phase.\n"
        "3. **Data Analysis**: Extract numerical data or trends from the citations.\n"
        "4. **Visualization**: Use the 'generate_and_upload_chart' tool to create and save a chart. "
        "Provide your matplotlib code, the SESSION_ID, and a SHORT_DESCRIPTIVE_NAME (no spaces) for the chart.\n"
        "5. **Finalize**: The tool will return a 'public_url'. Use 'record_chart_citation' to save this URL into the database using the SESSION_ID.\n\n"
        "If the question doesn't require a chart, just state that no visualization is needed."
    ),
    tools=[get_session_citations, generate_and_upload_chart, record_chart_citation]
)

root_agent = VisualizationAgent
