import os
import httpx
import logging
from typing import List, Dict, Any, Optional
from google import genai
from google.adk import Agent
from google.genai import types as genai_types
from langsmith import traceable
from dotenv import load_dotenv

from authenticated_httpx import create_authenticated_client

load_dotenv()

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# MCP Server URLs
DB_URL = os.getenv("MCP_DB_SERVER_URL", "http://localhost:8010")

# Initialize GenAI client using Vertex AI (uses ADC in Cloud Shell/Cloud Run)
genai_client = genai.Client(
    vertexai=True, 
    project=os.getenv("GCP_PROJECT_ID"), 
    location=os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1")
)

@traceable(run_type="tool", name="Synth_GetCitations")
async def get_session_citations(session_id: str) -> List[Dict[str, Any]]:
    """Fetch all citations for the current session for general analysis."""
    try:
        async with create_authenticated_client(DB_URL) as client:
            response = await client.post(f"{DB_URL}/tools/get_session_citations", json={"session_id": session_id.strip()}, timeout=30.0)
            response.raise_for_status()
            return response.json().get("results", [])
    except Exception as e:
        logger.error(f"DB MCP Error (get_session_citations): {e}")
        return []

@traceable(run_type="tool", name="Synth_SemanticLookup")
async def semantic_citation_lookup(session_id: str, query: str) -> List[Dict[str, Any]]:
    """Search for the most semantically relevant raw citations using vector similarity."""
    try:
        # 1. Generate embedding for the specific sub-query
        embed_res = genai_client.models.embed_content(
            model="text-embedding-004",
            contents=query,
            config=genai_types.EmbedContentConfig(task_type="RETRIEVAL_QUERY")
        )
        query_embedding = embed_res.embeddings[0].values

        # 2. Query DB MCP for semantic neighbors
        async with create_authenticated_client(DB_URL) as client:
            payload = {
                "session_id": session_id.strip(),
                "query_embedding": query_embedding,
                "top_k": 5
            }
            response = await client.post(f"{DB_URL}/tools/semantic_search_citations", json=payload, timeout=30.0)
            response.raise_for_status()
            return response.json().get("results", [])
    except Exception as e:
        logger.error(f"Semantic Search Error: {e}")
        return []

# Synthesizer Agent: Gemini 2.5 Pro
SynthesizerAgent = Agent(
    name="SynthesizerAgent",
    model="gemini-2.5-pro",
    description="Synthesizes research findings into a grounded report.",
    instruction=(
        "You are the Council Synthesizer. Your goal is to produce a 'Model Conclave Research Synthesis Report'.\n\n"
        "1. Extract the 'SESSION_ID' from the user prompt.\n"
        "2. Use 'get_session_citations' to see the breadth of research.\n"
        "3. For specific technical points or contentious claims, use 'semantic_citation_lookup' with a targeted query to find the most relevant raw evidence.\n"
        "4. **Visualizations**: Check the citations for any links to 'charts/' or images (e.g., .png, .jpg). These were generated by research agents using the code interpreter.\n"
        "5. Produce the final report matching this format:\n\n"
        "## Model Council Synthesis Report\n\n"
        "### Original Question\n"
        "[Restate user question]\n\n"
        "### 1. Where Models Agree\n"
        "Markdown table with citations. Reuse original source URLs.\n\n"
        "### 2. Where Models Disagree\n"
        "Markdown table showing different perspectives.\n\n"
        "### 3. Unique Discoveries\n"
        "Markdown table with unique insights.\n\n"
        "### 4. Visual Analysis\n"
        "If any charts or visualizations were generated during research, embed them here using markdown syntax: `![Chart Description](PUBLIC_URL)`. Provide a brief analytical summary of the chart.\n\n"
        "### 5. Synthesis & Grounded Conclusion\n"
        "Provide a high-confidence conclusion, using direct snippets retrieved via 'semantic_citation_lookup' where possible.\n\n"
        "CRITICAL: Be strictly grounded. If you find conflicting data, highlight it. Do NOT make up citations."
    ),
    tools=[get_session_citations, semantic_citation_lookup]
)

root_agent = SynthesizerAgent
